[package]
name = "tcp-receiver"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.11.0"
clap = { version = "4.5.54", features = ["derive"] }
pnet = "0.35.0"
tokio = { version = "1.48.0", features = ["full"] }
